FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ENV DEPLOY=true

RUN apt -y update && \
    apt -y install git && \
    apt -y install nodejs && \
    apt -y install npm

WORKDIR /serverchat/

RUN rm -rf serverchatjs/

RUN git clone https://github.com/carlosvalarezo/serverchatjs.git

WORKDIR /serverchat/serverchatjs/

RUN npm install

EXPOSE 8001

EXPOSE 27017

ENTRYPOINT ["npm", "start"]
