FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ENV DEPLOY=true

RUN apt -y update && \
    apt -y install git && \
    apt -y install nodejs && \
    apt -y install curl && \
    apt -y install sudo && \
    apt -y install gnupg2 && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
    sudo apt -y remove cmdtest && \
    sudo apt -y remove yarn && \
    sudo apt-get -y update  && \
    sudo apt-get -y install yarn

WORKDIR /chatui/

RUN rm -rf uichatjs/

RUN git clone https://github.com/carlosvalarezo/uichatjs.git

WORKDIR /chatui/uichatjs/

RUN yarn install

EXPOSE 3000

ENTRYPOINT ["yarn", "start", "&"]
